name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate prisma client
        run: pnpm prisma generate

      - name: Build the application
        run: pnpm run build

#   smoke-test:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '22'

#       - name: Install pnpm
#         run: npm install -g pnpm

#       - name: Install dependencies
#         run: pnpm install

#       - name: Generate prisma client
#         run: pnpm prisma generate

#       - name: Run smoke tests
#         run: pnpm run build && echo "Smoke test passed"
